apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vn78grkum-go 
  janus-idp.io/tekton: vn78grkum-go
  backstage.io/kubernetes-id: vn78grkum-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn78grkum-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  