apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: vn78grkum-go
  janus-idp.io/tekton: vn78grkum-go
  backstage.io/kubernetes-id: vn78grkum-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vn78grkum-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
