apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: vn78grkum-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: vn78grkum-go 
  name: vn78grkum-go
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: vn78grkum-go 
